global:
  useCombinedDb: true
  useCloudSql: false
  externalUrl: "http://localhost:6100"
  rollingUpdate:
    maxUnavailable: 0
  exposeNodePorts: false
  image:
    repository: "data61"
    pullPolicy: Always
  defaultAdminUserId: "00000000-0000-4000-8000-000000000000"
  logLevel: INFO
  noDbAuth: false
tags:
  all: true
  admin-api: false
  authorization-api: false
  authorization-db: false
  combined-db: false
  discussions-api: false
  discussions-db: false
  elasticsearch: false
  feedback: false
  gateway: false
  indexer: false
  preview-map: false
  registry-api: false
  registry-db: false
  search-api: false
  session-db: false
  sleuther-broken-link: false
  sleuther-linked-data-rating: false
  sleuther-visualization: false
  sleuther-format: false
  web-server: false
  kn-web-app: false
  dev-ingress: false
  kn-es-ingress: false
